### ISSUE TITLE
Unable to produce image from spring boot

### ISSUE THREAD

**Issue by sendev1** [ayltai/spring-graalvm-native-plugin#3]
**Describe the bug**
Unable to run the sample in github or unable to create native image for spring boot app that is downloaded from spring intializr web site. Please see attached screen shot. I am trying to create native image for spring boot app.

**To Reproduce**
For Sample tomcat app in your git I cloned the code and tried gradlw build and gradlew buildNativeImage. Please see screen shot for error.

For the spring boot app that I downloaded from spring intializr I was able to trigger gradlew buildNativeImage command but it fails to create image with error that ```
Cannot run program "native-image" (in directory "C:\dev\Work\Graal
\Workspace\ayltai\build\native"): CreateProcess error=2, The system cannot find the file specified
``` But I can see that folder exist

**Expected behavior**
Should able to create native image

**Screenshots**
If applicable, add screenshots to help explain your problem.
[ayltai-github sample app unable to run buildNativeImage.docx](https://github.com/ayltai/spring-graalvm-native-plugin/files/4954264/ayltai-github.sample.app.unable.to.run.buildNativeImage.docx)
[ayltai-spring initializr spring boot app native image error.docx](https://github.com/ayltai/spring-graalvm-native-plugin/files/4954265/ayltai-spring.initializr.spring.boot.app.native.image.error.docx)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Version [e.g. 10]

**Additional context**
Add any other context about the problem here.

**Comment by ayltai** [comment]
The sample (springmvc-tomcat) is not included in the root project (spring-graalvm-native-plugin), because a Gradle plugin project cannot use the plugin it creates. This is also reflected in `settings.gradle`, which does not include the sample project because the sample project simply does not belong to the Gradle plugin.

You can try one of these:
1. Use command line: Go to the sample project directory, and run `gradlew buildNativeImage`.
2. Open the sample project (not the plugin project) directly in your IDE.

Then, please update to use plugin v1.0.6 which fixes a bug when building on Windows. Note that there are additional [requirements](https://www.graalvm.org/docs/getting-started/windows) to build using GraalVM on Windows.

**Comment by ayltai** [comment]
v1.07 should fix the above issue. I'm closing this issue.
